### ISSUE TITLE
Hot keys not working since 1.4.4-2 on Debian testing 64-bit

### ISSUE THREAD

**Issue by stefanos82** [CristianHenzel/ClipIt#97]
Since 2018-07-12 that `clipit` got upgraded to version 1.4.4-2, its hotkeys are not working at all.

When I press `Ctrl-Alt-F` to open `Manage History`, it doesn't do anything at all.

When I press `Ctrl-Alt-H` to open `History`, I get the following window:

![image](https://user-images.githubusercontent.com/1777466/43056584-acb4bfe4-8e45-11e8-9bc4-66c57c3c887a.png)

Can we do something about it?

**Comment by stefanos82** [comment]
Update: There is another issue thanks to this hotkeys' complexity.

When you go to `Manage History` and delete a line from your history, by revisiting your `Manage History` you can see the line retaining its space, but without the actual string in it.

As soon as you delete the empty line, it automatically deletes the immediate next line.

This behavior is rather critical in my humble opinion.

**Comment by Darcidride** [comment]
Hi, same issue here : 
![image](https://user-images.githubusercontent.com/8619233/43458529-d8011694-94ca-11e8-87ee-a52bb8412e8e.png)
the history pannel is like this, and the preferences panel is freezed after a first click inside it, also the hotkeys to access history clipboard doesn't work anymore...

Some logs : 
```
(clipit:24858): Gtk-CRITICAL **: 14:06:37.634: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(clipit:24858): Gtk-CRITICAL **: 14:06:37.641: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(clipit:24858): Gtk-CRITICAL **: 14:06:37.649: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(clipit:24858): Gtk-CRITICAL **: 14:06:37.650: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(clipit:24858): Gtk-CRITICAL **: 14:06:37.658: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(clipit:24858): Gtk-CRITICAL **: 14:06:37.666: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(clipit:24858): Gtk-CRITICAL **: 14:06:37.674: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(clipit:24858): Gtk-CRITICAL **: 14:06:37.681: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(clipit:24858): Gtk-CRITICAL **: 14:06:37.681: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(clipit:24858): Gtk-CRITICAL **: 14:06:37.689: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(clipit:24858): Gtk-CRITICAL **: 14:06:37.689: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Clipboard is null, recovering ...
Clipboard is null, recovering ...
Clipboard is null, recovering ...
Clipboard is null, recovering ...
Clipboard is null, recovering ...
Clipboard is null, recovering ...
Clipboard is null, recovering ...
Clipboard is null, recovering ...
Clipboard is null, recovering ...
Clipboard is null, recovering ...
Clipboard is null, recovering ...
```

I don't know how to fix it, please help us :)

**Comment by swillner** [comment]
I have the same problem, but could not reproduce the error when custom building from the debian package source directory (https://salsa.debian.org/debian/clipit.git). Looks like it is an issue of the build itself...

**Comment by stefanos82** [comment]
@swillner When you say custom building, what exactly did you change comparing the original build?

**Comment by swillner** [comment]
I build directly from the debian source repo (using `./autogen.sh` and `./configure` as in the documentation)

**Comment by stefanos82** [comment]
@swillner ah OK, cool. Hmm...I wonder what's causing this problem with the existing package.

**Comment by proft** [comment]
Hi!

The same error:

```
uname -a                                                                                                                                              ~/
Linux archlinux 4.17.13-arch1-1-ARCH #1 SMP PREEMPT Mon Aug 6 23:06:31 UTC 2018 x86_64 GNU/Linux
```

```
clipit:8228): Gdk-CRITICAL **: 22:39:04.104: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(clipit:8228): Gdk-CRITICAL **: 22:39:04.425: gdk_window_get_pointer: assertion 'GDK_IS_WINDOW (window)' failed

(clipit:8228): Gdk-CRITICAL **: 22:39:04.927: gdk_window_get_pointer: assertion 'GDK_IS_WINDOW (window)' failed

(clipit:8228): Gdk-CRITICAL **: 22:39:05.430: gdk_window_get_pointer: assertion 'GDK_IS_WINDOW (window)' failed

(clipit:8228): Gdk-CRITICAL **: 22:39:05.931: gdk_window_get_pointer: assertion 'GDK_IS_WINDOW (window)' failed

(clipit:8228): GLib-GObject-CRITICAL **: 22:39:06.323: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed

(clipit:8228): Gdk-CRITICAL **: 22:39:06.434: gdk_window_get_pointer: assertion 'GDK_IS_WINDOW (window)' failed
```

**Comment by jazbina** [comment]
Same issue here
https://github.com/CristianHenzel/ClipIt/issues/101#issuecomment-414144952

**Comment by medisun** [comment]
Same issue with version 1.4.4-8 on Manjaro/Arch linux
```
(clipit:7411): Gdk-CRITICAL **: 12:59:18.073: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
(clipit:7411): Gdk-CRITICAL **: 12:59:18.421: gdk_window_get_pointer: assertion 'GDK_IS_WINDOW (window)' failed
(clipit:7411): GLib-GObject-CRITICAL **: 12:59:19.187: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed
(clipit:7411): Gdk-CRITICAL **: 12:59:19.428: gdk_window_get_pointer: assertion 'GDK_IS_WINDOW (window)' failed
```
had to rollback on version 1.4.3-2.
Used libraries
```sh
ldd $(which clipit)
	linux-vdso.so.1 (0x00007ffc475b2000)
	libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0 (0x00007f90814c4000)
	libgdk-x11-2.0.so.0 => /usr/lib/libgdk-x11-2.0.so.0 (0x00007f9081210000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007f9080fbc000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f9080ca5000)
	libappindicator.so.1 => /usr/lib/libappindicator.so.1 (0x00007f9080a98000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f9080759000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f9080593000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007f908038f000)
	libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007f9080182000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f907ff7c000)
	libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x00007f907fd56000)
	libcairo.so.2 => /usr/lib/libcairo.so.2 (0x00007f907fa33000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x00007f907f80d000)
	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x00007f907f46d000)
	libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007f907f258000)
	libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x00007f907f011000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f907edce000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f907ec49000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f907ec26000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f907ea1b000)
	libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007f907e818000)
	libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f907e607000)
	libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007f907e3fc000)
	libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007f907e1f2000)
	libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x00007f907dfed000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007f907ddea000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f907dbd8000)
	libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f907d9cf000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f907d75d000)
	libindicator.so.7 => /usr/lib/libindicator.so.7 (0x00007f907d54f000)
	libdbusmenu-gtk.so.4 => /usr/lib/libdbusmenu-gtk.so.4 (0x00007f907d339000)
	libdbusmenu-glib.so.4 => /usr/lib/libdbusmenu-glib.so.4 (0x00007f907d11d000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f907ce54000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f907cc2b000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f907cc26000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f9081b4c000)
	libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x00007f907c97c000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f907c746000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x00007f907c542000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x00007f907c334000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f907c11d000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f907c113000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f907c0f8000)
	libmount.so.1 => /usr/lib/libmount.so.1 (0x00007f907be9f000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f907bdea000)
	libthai.so.0 => /usr/lib/libthai.so.0 (0x00007f907bbe0000)
	libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x00007f907b9c4000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f907b792000)
	libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f907b589000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f907b379000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f907b175000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f907af6f000)
	libblkid.so.1 => /usr/lib/libblkid.so.1 (0x00007f907ad1c000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f907aaf0000)
	libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x00007f907a8e9000)
```
glib2 is 2.56.1-1

**Comment by LorincJuraj** [comment]
Same issue with version 1.4.4-2 after updating to Ubuntu from 18.04 to 18.10. Temporary fixed by  reinstalling lower version (1.4.2-1.2) of ClipIt from [pkgs.org](https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/clipit_1.4.2-1.2_amd64.deb.html)

**Comment by trumberto** [comment]
I got similar errors as @emjayko:

> (clipit:7183): GLib-GObject-CRITICAL **: 20:56:43.530: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed
> (clipit:7183): Gdk-CRITICAL **: 20:56:43.530: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
> ```

I found out, that if I hold the hotkey long enough, the history window appears.

**Comment by sdragnev** [comment]
Exact same issue for me with the latest master (looks like version string has been updated to 1.4.5), built with --with-gtk3. There were some deprecation warnings during configure but it finished fine.
There's definitely been some recent improvements because even compiling wasn't completing for me a few months ago.

But I guess this particular issue is still to be fixed.

**Comment by brother** [comment]
> I found out, that if I hold the hotkey long enough, the history window appears.

THANK YOU!

**Comment by J-Reis** [comment]
I now have this issue in Debian Stable 10 … unsurprisingly I guess. ClipIt version 1.4.4 from debian buster repo. Problem exactly as described above, hotkeys do not work. Terminal shows error:
`(clipit:1000): Gdk-CRITICAL **: 19:03:32.292: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed` when hotkey is pressed.

Possibly related: If I interact with the tray icon and pull up preferences, about, etc. they work fine. However if I try to use, for instance the History hotkey (as usual nothing happens on key press), but if I then try to open one of the dialogue/windows such as preferences or the about page, etc I will get a small black rectangle in the upper left portion of my screen, the intended window never appears and ClipIt must be killed to get rid of the black rectangle.
Behavior is the same using jwm or fluxbox.

**Comment by johntyree** [comment]
So is this project dead or what? Completely broken across many distributions and not a peep :(

**Comment by J-Reis** [comment]
> So is this project dead or what? Completely broken across many distributions and not a peep :(

I cannot speak for the ClipIt project in any way and cannot comment on whether the project has any life in it at this time or not. For what it's worth, I personally have moved over to using [GPaste](https://github.com/Keruspe/GPaste). Which is in the Debian repos and works very well. I post this, not to impugn the ClipIt project in any way, or even to claim that GPaste is the best alternative (indeed, there seem to be many) … but only in the hopes that it may help users who are presently encountering a functionality breaking issue and looking for a relatively quick & painless fix.

**Comment by onlyjob** [comment]
Thanks, @J-Reis. Personally I've settled on [Clipman](https://goodies.xfce.org/projects/panel-plugins/xfce4-clipman-plugin) (provided by _xfce4-clipman_ package) -- lightweight, stable and DE-neutral.
_GPaste_ is too GNOME-centric for those who prefer other Desktop Environments...

**Comment by J-Reis** [comment]
I hesitate to continue hijacking this thread discussing replacements, but I'm not sure what you've said is really true. I'm not running gnome, just a window manager on top of X and I don't recall GPaste pulling in a significant number of dependencies. Of course, I habitually choose the application that works best for me—I don't disregard anything solely on the basis of what libraries it uses, so perhaps my system is just massively bloated and all those Gnome dependencies were already present. Since I'm no expert, I just did a quick check of dependencies using apt (obviously the specifics are a bit Debian centric, but the general trend should hold regardless of system):
<details>
<summary>Depencies list</summary><p>

XFCE-clipman | GPaste
|---------------------------------------------------------------------|---------------------------------------------|
| libc6 (>= 2.4)                                                      | dconf-gsettings-backend | gsettings-backend |
| libgdk-pixbuf2.0-0 (>= 2.22.0)                                      | &nbsp;&nbsp;&nbsp;&nbsp; > dconf-service (>= 0.30.1-2)                 |
| libglib2.0-0 (>= 2.37.3)                                            | &nbsp;&nbsp;&nbsp;&nbsp; > libdconf1 (= 0.30.1-2)                      |
| libgtk-3-0 (>= 3.19.12)                                             | libc6 (>= 2.4)                              |
| libqrencode4 (>= 3.2.0)                                             | libglib2.0-0 (>= 2.58.0~)                   |
| libx11-6                                                            | libgpaste11 (>= 3.28.2)                     |
| libxfce4ui-2-0 (>= 4.11.0)                                          | &nbsp;&nbsp;&nbsp;&nbsp; > libatk1.0-0 (>= 1.12.4)                     |
| &nbsp;&nbsp;&nbsp;&nbsp; > libatk1.0-0 (>= 1.12.4)                                             | &nbsp;&nbsp;&nbsp;&nbsp; > libc6 (>= 2.4)                              |
| &nbsp;&nbsp;&nbsp;&nbsp; >libc6 (>= 2.4)                                                      | &nbsp;&nbsp;&nbsp;&nbsp; > libcairo-gobject2 (>= 1.10.0)               |
| &nbsp;&nbsp;&nbsp;&nbsp; >libcairo-gobject2 (>= 1.10.0)                                       | &nbsp;&nbsp;&nbsp;&nbsp; > libcairo2 (>= 1.2.4)                        |
| &nbsp;&nbsp;&nbsp;&nbsp; >libcairo2 (>= 1.2.4)                                                | &nbsp;&nbsp;&nbsp;&nbsp; > libgdk-pixbuf2.0-0 (>= 2.31.1)              |
| &nbsp;&nbsp;&nbsp;&nbsp; >libdbus-1-3 (>= 1.9.14)                                             | &nbsp;&nbsp;&nbsp;&nbsp; > libglib2.0-0 (>= 2.58.0~)                   |
| &nbsp;&nbsp;&nbsp;&nbsp; >libdbus-glib-1-2 (>= 0.78)                                          | &nbsp;&nbsp;&nbsp;&nbsp; > libgtk-3-0 (>= 3.24)                        |
| &nbsp;&nbsp;&nbsp;&nbsp; >libgdk-pixbuf2.0-0 (>= 2.22.0)                                      | &nbsp;&nbsp;&nbsp;&nbsp; > libpango-1.0-0 (>= 1.14.0)                  |
| &nbsp;&nbsp;&nbsp;&nbsp; >libglib2.0-0 (>= 2.37.3)                                            | &nbsp;&nbsp;&nbsp;&nbsp; > libpangocairo-1.0-0 (>= 1.14.0)             |
| &nbsp;&nbsp;&nbsp;&nbsp; >libgtk-3-0 (>= 3.9.12)                                              | &nbsp;&nbsp;&nbsp;&nbsp; > libx11-6                                    |
| &nbsp;&nbsp;&nbsp;&nbsp; > libice6 (>= 1:1.0.0)                                                | &nbsp;&nbsp;&nbsp;&nbsp; > libxi6 (>= 2:1.2.99.4)                      |
| &nbsp;&nbsp;&nbsp;&nbsp; > libpango-1.0-0 (>= 1.14.0)                                          | &nbsp;&nbsp;&nbsp;&nbsp; > &nbsp;&nbsp;&nbsp;&nbsp; > libxext6                                    |
| &nbsp;&nbsp;&nbsp;&nbsp; >libpangocairo-1.0-0 (>= 1.14.0)                                     | libgtk-3-0 (>= 3.24)                        |
| &nbsp;&nbsp;&nbsp;&nbsp; > libsm6                                                              |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > &nbsp;&nbsp;&nbsp;&nbsp; >libc6 (>= 2.14), libice6 (>= 1:1.0.0), libuuid1 (>= 2.16)           |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; >libstartup-notification0 (>= 0.4)                                   |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; >&nbsp;&nbsp;&nbsp;&nbsp; > libc6 (>= 2.4), libx11-xcb1, libxcb-util0 (>= 0.3.8), libxcb1       |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > libx11-6                                                            |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > libxfce4util7 (>= 4.9.0)                                            |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > libxfconf-0-2 (>= 4.6.0)                                            |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > libxfce4ui-common (>= 4.11)                                         |                                             |
| libxfce4util7 (>= 4.9.0)                                            |                                             |
| libxfconf-0-2 (>= 4.6.0)                                            |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > libc6 (>= 2.14)                                                     |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > libdbus-1-3 (>= 1.9.14)                                             |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > libdbus-glib-1-2 (>= 0.78)                                          |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > libglib2.0-0 (>= 2.41.1)                                            |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > xfconf                                                              |                                             |
| libxtst6                                                            |                                             |
| &nbsp;&nbsp;&nbsp;&nbsp; > libc6 (>= 2.4), libx11-6 (>= 2:1.6.0), libxext6, libxi6, x11-common |                                             |
</p></details>

Do let me know if I'm failing to understand something here, I'm always trying to learn!

**Comment by stefanos82** [comment]
Seems like we have some progress...

On my system, version 1.4.5 is installed and when I press `Ctrl+Alt+F`, I get a popup window to search my clipboard.

If I press `Ctrl+Alt-H` though, it behaves as my original report.

**Comment by johntyree** [comment]
fwiw I liked the project and it did everything I wanted, but I've moved on to parcellite, which is worse but better because it works. :/

I get that it's OSS and we're all busy people, but I'm honestly pretty confused that this change wasn't just rolled back. "Hotkeys don't work" is a showstopper.

**Comment by fabzgy** [comment]
> Seems like we have some progress...
> 
> On my system, version 1.4.5 is installed and when I press `Ctrl+Alt+F`, I get a popup window to search my clipboard.
> 
> If I press `Ctrl+Alt-H` though, it behaves as my original report.

Where dou you got the 1.4.5 Version from? Have not seen any release yet.
I ve just upgraded from Ubuntu 19.04 to 19.10 and installed / downgraded to clipit_1.4.2-1.2_amd64.deb which unfortunately does not work anymore as in 19.04.
So either I find this 1.4.5 Version or I need to use another Clipboard Manager since working without one seems to be a nightmare!f

**Comment by stefanos82** [comment]
Please read my ticket's title.

**Comment by jemyzhang** [comment]
@CristianHenzel @stefanos82 
When I use gdb to debug this issue, I found that if a create a break point at `create_history_menu`, and just `c`ontinue to run after break stopped, everything goes fine, but I have no idea about it, I just wondering is the POPUP_DELAY is too small, something is not ready?

So I try to increase the POPUP_DELAY, and then every thing ok, amazing.
But sorry to all, I don't know the reason. lol

**Comment by scythargon** [comment]
I'd like to increase POPUP_DELAY, but failed to compile it from source.
Ubuntu 19.10
`main.c:211:7: error: unknown type name ‘GdkSeat’; did you mean ‘GdkSpan’?`

**Comment by jemyzhang** [comment]
> I'd like to increase POPUP_DELAY, but failed to compile it from source.
> Ubuntu 19.10
> `main.c:211:7: error: unknown type name ‘GdkSeat’; did you mean ‘GdkSpan’?`

Try to configure with gtk3

```
./configure --with-gtk3 --enable-appindicator=yes
```

**Comment by antonioromito** [comment]
Same issue here with Fedora 31, kernel-5.3.13-300, and clipit-1.4.4-5.fc31.x86_64

**Comment by SuzanaK** [comment]
Same problem with Ubuntu 19.10 and clipit-1.4.4+git20190202-1.

**Comment by SuzanaK** [comment]
> Same issue with version 1.4.4-2 after upgrading Ubuntu from 18.04 to 18.10. Temporary fixed by reinstalling lower version (1.4.2-1.2) of ClipIt from [pkgs.org](https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/clipit_1.4.2-1.2_amd64.deb.html)

That made the hotkeys work but then their functionality broke - the actions aren't executed and the history stays always empty.

**Comment by azadpsg** [comment]
same problem here
has anyone found anyway?

**Comment by xamox** [comment]
Harsh, I love clipit, been using it for years, recently upgraded to 19.10 and now it's not working. :(

**Comment by IPWright83** [comment]
I've just noticed this, took me a while to work out why shortcut keys weren't doing anything in other applications but also did nothing in Ubuntu.

Is it possible to install an older working version? I tried to follow the instructions from @Darcidride but unfortunately I got an error trying to use the `-t stretch` parameter.

**Comment by SuzanaK** [comment]
> I've just noticed this, took me a while to work out why shortcut keys weren't doing anything in other applications but also did nothing in Ubuntu.
> 
> Is it possible to install an older working version? I tried to follow the instructions from @Darcidride but unfortunately I got an error trying to use the `-t stretch` parameter.

Yes, it is possible to use version 1.4.2-1.2 (works fine for me on Ubuntu 19.10)

**Comment by IPWright83** [comment]
@SuzanaK thanks, would you mind explaining how I might do so? Sorry I'm an Linux n00b!

**Comment by SuzanaK** [comment]
> @SuzanaK thanks, would you mind explaining how I might do so? Sorry I'm an Linux n00b!

I downloaded the `.deb` file from [here](https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/clipit_1.4.2-1.2_amd64.deb.html) and installed it (in Ubuntu you can install `.deb` files with right mouse click or in the terminal via `sudo dpkg -i <xyz.deb>`.

**Comment by brother** [comment]
> > @SuzanaK thanks, would you mind explaining how I might do so? Sorry I'm an Linux n00b!
> 
> I downloaded the `.deb` file from [here](https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/clipit_1.4.2-1.2_amd64.deb.html) and installed it (in Ubuntu you can install `.deb` files with right mouse click or in the terminal via `sudo dpkg -i <xyz.deb>`).

I would actually suggest using apt to install the deb file as it would take care of dependencies as well. In this case I guess it's a nonissue but for future references.

(just do `sudo apt install ./my.deb`)

**Comment by xamox** [comment]
The old version worked.  Thanks!

**Comment by stefanos82** [comment]
Today I was informed by my upgrade procedure that clipit has been replaced with [diodon](https://packages.debian.org/bullseye/diodon).

I have tried to use it and didn't like it at all.

I guess it's a goodbye to those projects for me :shrug:

**Comment by xamox** [comment]
@stefanos82 I recently came across: https://extensions.gnome.org/extension/779/clipboard-indicator/.  That has been working pretty well for me.

**Comment by stefanos82** [comment]
I decided to use the XFCE4 clipboard and it's quite easy to use.

It has its own history mechanism that you can use much like clipit.

All you need to do is to assign it to a hotkey shortcut and that would be it, really.

**Comment by mckellyln** [comment]
Do either of those allow for keeping clipboard and primary in sync ?

**Comment by stefanos82** [comment]
> Do either of those allow for keeping clipboard and primary in sync ?

@mckellyln When you say primary, what exactly do you mean?

Can you explain it to me please as I'm not a native English speaker?

**Comment by mckellyln** [comment]
Many clipboard managers keep the primary and selection clipboard "in sync" at least as an option.
X11 has 2 clipboards (3 actually) and keyboard ctrl+c / ctrl+v ususally is connected to one clipboard and mouse drag+copy usually goes to another clipboard.  If the clipboard manager keeps them in sync then you can drag+copy with mouse and ctrl+v with keyboard to get the same result.
I am just asking of there is an option such as "sync clipboards" you can select if you want.

**Comment by stefanos82** [comment]
You mean this?

![image](https://user-images.githubusercontent.com/1777466/81319435-54c75600-9098-11ea-97dc-88d250c0223f.png)

From `Paste instantly` you get three options: `None`, `Ctrl+V`, and `Shift+Insert`

I hope this helps.

**Comment by mckellyln** [comment]
I am not sure, it does not seem clear to me from the words above.
I was only trying to find out, as if it does not support this then I would keep looking for a clipbaord manager that does support it :-)

**Comment by stefanos82** [comment]
When I hovered over `Sync mouse selections`, I get the following message tooltip: 

> If checked, the selections will be synced with the default clipboard in a way that you can paste what you select

Does this help a bit more this time?

**Comment by mckellyln** [comment]
Yes, that does seem more like the same as keeping the clipboards in sync.

**Comment by afelinczak** [comment]
This is fixed in 1.4.5.
I will sync missing patches from this version to my ppa and also build deb package.
https://launchpad.net/~afelinczak/+archive/ubuntu/ppa
Issue is not related to hotkeys - it is problem with GtkMenu.

**Comment by afelinczak** [comment]
Hey,
It may be related to how deb package is compiled. Clipit compile scripts has flag enable-appindicator, switching it can help.

I may prepare second deb package, but for next 2-3 weeks Im very busy and cant promise any date.

**Comment by Darcidride** [comment]
Thank you for your quick answer

No problem, we will do as in for a few weeks

We're very grateful for your fix, keep your time :)

**Comment by afelinczak** [comment]
@Darcidride uploaded deb file with app indicator flag on.
Please let me know if this fix icon issue.

**Comment by Darcidride** [comment]
@afelinczak  Still no icon in my side

I'm using this verison of clipit from your personal repo (focal verison)
```
clipit:
  Installed: 1.4.5+git20200624-1ppa1
  Candidate: 1.4.5+git20200624-1ppa1
  Version table:
 *** 1.4.5+git20200624-1ppa1 500
        500 http://ppa.launchpad.net/afelinczak/ppa/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     1.4.4+git20190202-2 900
        100 https://deb.debian.org/debian unstable/main amd64 Packages
        900 https://deb.debian.org/debian testing/main amd64 Packages
     1.4.4+git20190202-1 -20
        -20 https://deb.debian.org/debian stable/main amd64 Packages
```

Some more inforamtions if it can help :
```
$ uname -a
Linux LUNE 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
```
```
$ cat /etc/debian_version
bullseye/sid
```
```
gdm3 --version
GDM 3.36.3
```

But clipit is working great, i'm using it with shortcuts, just no gdm3 con

**Comment by afelinczak** [comment]
hey @Darcidride 
Sorry for misunderstanding - I uploaded deb file here on github (release section) not to ppa.
I may get 2 versions to ppa but on daily basis I'm using Ubuntu Mate and current PPA version works ok for me.
Please check this one and let me know if icon works
https://github.com/CristianHenzel/ClipIt/releases/download/v1.4.5/clipit_1.4.5_amd64_indicator.deb

**Comment by Darcidride** [comment]
Hi @afelinczak 
I installed the version linked from the GitHub link
The app indicator is there ! :+1: 
I needed to force install since the semversioning is older than the other one I installed, and I `apt-mark hold` this package just in case

Well, everything is working perfectly in my side, thank you very much for your fix !

**Comment by afelinczak** [comment]
Im not sure if anyone tested on 19.10 @SuzanaK but from the error message I would check if any other app is not using same hotkeys as clipit.
I assume you are using deb file from third post above?

**Comment by afelinczak** [comment]
Please verify all bindings are free:

History | Ctrl + Alt + h
Actions | Ctrl + Alt + a
Menu | Ctrl + Alt + p
Search | Ctrl + Alt + f
Offline mode | Ctrl + Alt + o

**Comment by SuzanaK** [comment]
Yes, everyone of those is free. But I don' t think that's the problem - the whole app won't start without throwing an error.

**Comment by SuzanaK** [comment]
Sorry, the failure to start has nothing to do with clipit - I have it with other apps, too.
(journalctl is showing `Fatal IO error 11 (Resource temporarily unavailable) on X server :1.`)

**Comment by afelinczak** [comment]
@SuzanaK I tried to test this Today, but 19.10 has reached end of life and I was unable to install clipit as ubuntu repos are not active anymore.
I suggest upgrade to 20.04 LTS.

**Comment by Darcidride** [comment]
Maybe someone can add a comment on this project readme, under discontinued, to inform that we can use this package instead of moving to another tool

**Comment by afelinczak** [comment]
@Darcidride good idea, I have PR open related to meson, will add note to readme.

**Comment by jekeam** [comment]
> ## Same issue in my case (Debian testing)
> Hi, same issue here :
> ![image](https://user-images.githubusercontent.com/8619233/43458529-d8011694-94ca-11e8-87ee-a52bb8412e8e.png)
> The history pannel is like this, and the preferences panel is freezed after a first click inside it, also the hotkeys to access history clipboard doesn't work anymore...
> 
> Some logs :
> 
> ```
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.634: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.641: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.649: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.650: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.658: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.666: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.674: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.681: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.681: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.689: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> 
> (clipit:24858): Gtk-CRITICAL **: 14:06:37.689: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
> Clipboard is null, recovering ...
> Clipboard is null, recovering ...
> Clipboard is null, recovering ...
> Clipboard is null, recovering ...
> Clipboard is null, recovering ...
> Clipboard is null, recovering ...
> Clipboard is null, recovering ...
> Clipboard is null, recovering ...
> Clipboard is null, recovering ...
> Clipboard is null, recovering ...
> Clipboard is null, recovering ...
> ```
> 
> I don't know how to fix it, please help us :)
> 
> ## System informations
> uname -a :
> `Linux oab-cycd9w1 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux`
> 
> cat /etc/debian_version : `buster/sid`
> 
> ## Temporary solution
> Since i didn't see any news about a potential fix, I removed my clipit version and switch to the 1.4.2 version for the strethc repository.
> 
> If you also need this, here is the steps :
> 
> 1. Check the different version you can install
> 
> ```
> $ apt-cache policy clipit
> clipit:
>   Installed: 1.4.2-1.2
>   Candidate: 1.4.4-2
>   Version table:
>  *** 1.4.4-2 900
>         900 http://http.debian.net/debian buster/main amd64 Packages
>         -10 http://http.debian.net/debian unstable/main amd64 Packages
>      1.4.2-1.2 100
>         -20 http://httpredir.debian.org/debian stretch/main amd64 Packages
>         100 /var/lib/dpkg/status
> ```
> 
> (in my case i'm on Debian testing, so i installed the 1.4.4-2 version of clipit from 'buster/testing' repository)
> 
> 1. Then remove clipit (don't purge it, you will loose all your preferences)
>    `$ sudo apt autoremove clipit`
> 2. Now install again clipit but from the repository you want, in my case 'stretch/stable' repository
>    `$ sudo apt install -t stretch clipit`
> 3. Finally, check the installed version :
> 
> ```
> $ apt-cache policy clipit
> clipit:
>   Installed: 1.4.2-1.2
>   Candidate: 1.4.4-2
>   Version table:
>      1.4.4-2 900
>         900 http://http.debian.net/debian buster/main amd64 Packages
>         -10 http://http.debian.net/debian unstable/main amd64 Packages
>  *** 1.4.2-1.2 100
>         -20 http://httpredir.debian.org/debian stretch/main amd64 Packages
>         100 /var/lib/dpkg/status
> ```
> 
> Enjoy, you will now be able to launch again clipit without a freezed preference panel and with an hotkey working. (and everything else)

![Screenshot from 2021-01-18 12-28-20](https://user-images.githubusercontent.com/19660852/104884833-d2ae6180-5988-11eb-81a8-d5f7dbfbea31.png)
E: The value 'stretch' is invalid for APT::Default-Release as such a release is not available in the sources

**Comment by rfc2119** [comment]
On Debian buster, you need to hold down your shortcut in order for it to be activated (as stated by one of the commenters above). Indeed, it seems the `POPUP_DELAY` is **too large**. Also, as described by one user above, sometimes a black rectangle screen pops up on the top left of my screen. Only killing clipit removes it.

Is there a way to configure `POPUP_DELAY` without compiling from source ?
